# Generated by Django 4.2.13 on 2024-06-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_ourteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
    ]
