# Generated by Django 4.2.13 on 2024-06-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_ourclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('src', models.FileField(upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('video', models.FileField(blank=True, help_text='Upload your video here', upload_to='videos/')),
                ('video_url', models.URLField(blank=True)),
                ('poster', models.FileField(upload_to='videos/posters/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
