# Generated by Django 4.2.13 on 2024-06-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='message',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
