# Generated by Django 4.2.13 on 2024-06-12 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_donation_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='')),
                ('description', models.TextField()),
            ],
        ),
    ]
