# Generated by Django 4.2.13 on 2024-06-14 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
