# Generated by Django 4.2.13 on 2024-06-15 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_delete_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourteam',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
