# Generated by Django 4.2.13 on 2024-06-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_ourteam_bio_alter_ourteam_facebook_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourteam',
            options={'ordering': ['hierarchy_level']},
        ),
        migrations.AddField(
            model_name='ourteam',
            name='hierarchy_level',
            field=models.IntegerField(default=100),
        ),
    ]
