# Generated by Django 4.2.13 on 2024-06-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_alter_ourteam_options_ourteam_hierarchy_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='donations/images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='src',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='ourclient',
            name='image',
            field=models.ImageField(upload_to='clients/images/'),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='photo',
            field=models.ImageField(upload_to='team/photos/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='avatar',
            field=models.ImageField(upload_to='testimonials/avatars/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='poster',
            field=models.ImageField(upload_to='videos/posters/'),
        ),
    ]
