# Generated by Django 4.2.13 on 2024-06-05 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_is_featured'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
