# Generated by Django 4.2.13 on 2024-06-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_blog_slug_alter_publication_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='social_links',
        ),
        migrations.AddField(
            model_name='author',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='whatsapp',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SocialLinks',
        ),
    ]
