# Generated by Django 4.2.13 on 2024-06-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pdf',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
