# Generated by Django 4.2.13 on 2024-06-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_event_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='cover',
            field=models.ImageField(upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='hero',
            field=models.ImageField(upload_to='heroes/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_thumbnail',
            field=models.ImageField(upload_to='category_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='cover',
            field=models.ImageField(upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='hero',
            field=models.ImageField(upload_to='heroes/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pdf',
            field=models.FileField(upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='cover',
            field=models.ImageField(upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='hero',
            field=models.ImageField(upload_to='heroes/'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pdf',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
