# Generated by Django 4.2.13 on 2024-06-18 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_author_avatar_alter_blog_cover_alter_blog_hero_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-created_at']},
        ),
    ]
