# Generated by Django 4.2.13 on 2024-06-19 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_blog_options_alter_event_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=1000, null=True, unique=True)),
                ('title', models.CharField(max_length=1000)),
                ('is_featured', models.BooleanField(default=False)),
                ('hero', models.ImageField(upload_to='heroes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover', models.ImageField(upload_to='covers/')),
                ('duration', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('pdf', models.FileField(upload_to='pdfs/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.opportunitytype')),
                ('tags', models.ManyToManyField(to='blog.tag')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
