# Generated by Django 4.2.13 on 2024-06-19 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_opportunitytype_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunitytype',
            old_name='name',
            new_name='title',
        ),
    ]
