# Generated by Django 4.2.13 on 2024-06-21 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_rename_name_opportunitytype_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunities_as_subcategory', to='blog.opportunitytype'),
        ),
        migrations.AddField(
            model_name='opportunitytype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='blog.opportunitytype'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='blog.opportunitytype'),
        ),
    ]
