# Generated by Django 4.2.13 on 2024-07-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_opportunity_subcategory_opportunitytype_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('slug', models.SlugField(blank=True, max_length=1000, null=True, unique=True)),
                ('location', models.CharField(max_length=2000)),
                ('salary', models.CharField(max_length=2000)),
                ('type', models.CharField(max_length=2000)),
                ('experience', models.CharField(max_length=2000)),
                ('level', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover', models.ImageField(upload_to='covers/')),
                ('deadline', models.DateField()),
                ('description', models.TextField(max_length=2000)),
                ('content', models.TextField()),
                ('urgent', models.BooleanField(default=False)),
                ('skills', models.ManyToManyField(to='blog.skills')),
            ],
        ),
    ]
