# Generated by Django 4.2.13 on 2024-07-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_skills_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
