# Generated by Django 4.2.13 on 2024-06-09 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfigs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donation',
            new_name='DonationContent',
        ),
    ]
