# Generated by Django 4.2.13 on 2024-06-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfigs', '0002_rename_donation_donationcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationcontent',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
