# Generated by Django 4.2.13 on 2024-09-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfigs', '0003_donationcontent_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('member_type', models.CharField(choices=[('supporting', 'Supporting Member'), ('contributing', 'Contributing Member')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('education', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('contribution_area', models.TextField(blank=True, null=True)),
                ('contribution_type', models.CharField(blank=True, choices=[('intellectual', 'Intellectually'), ('volunteer', 'Volunteer'), ('financial', 'Financially')], max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Newsletter Member',
                'verbose_name_plural': 'Newsletter Members',
            },
        ),
    ]
